language: java
addons:
  apt:
    packages:
    - libxml-xpath-perl
sudo: required
services:
- docker
jdk:
- oraclejdk8

before_install:
- "./src/main/scripts/ci/before-install.sh"
- "./src/main/scripts/cd/before-deploy.sh"
after_success:
- java -jar ~/codacy-coverage-reporter-assembly.jar -l Java -r ./services/target/site/jacoco/jacoco.xml
deploy:
- provider: script
  script: mvn -P release deploy -DskipTests=true -B -V -s travis-settings.xml
  on:
    branch: develop
- provider: script
  script:
  - "./src/main/scripts/cd/deploy.sh"
  on:
    branch: master

